# Generated by Django 3.2.9 on 2022-05-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page',
            new_name='pages',
        ),
    ]
